import { Product } from "./types";

export const products: Product[] = [
  {
    id: "sentinel-research",
    name: "Sentinel Research Infiltrator (Deep Intelligence)",
    description: "An autonomous deep-research AI agent. Give it a topic and it infiltrates the surface and deep web to synthesize a professional intelligence report — automatically. Powered by Perplexity and Firecrawl for unparallelled market visibility.",
    price: 2799,
    category: "AI Agents",
    image: "/images/products/sentinel-research.png",
    inStock: true,
    rating: 5.0,
    features: ['Autonomous Deep Web Scrape', 'Dual-Agent Synthesis Architecture', 'Cyberpunk Streamlit UI', 'Perplexity Research Uplink', 'Full Source Code Included'],
    specs: { API: 'OpenAI, Firecrawl, Perplexity', Format: 'Python / Streamlit', License: 'Master Resell Rights (MRR)', Support: 'Priority Support', Components: '2 Agents + UI' },
    downloadUrl: "/downloads/sentinel-research.zip",
    installGuide: "### Strategic Deployment\n1. **Environment**: Python 3.10+ required.\n2. **Setup**: \n   ```bash\n   pip install -r requirements.txt\n   cp .env.example .env\n   ```\n3. **Uplink**: Add `PERPLEXITY_API_KEY` and `FIRECRAWL_API_KEY` to `.env`.\n4. **Launch**: `python intel.py` or `streamlit run app.py`.\n\n### Usage Manual\nProvide 3 competitor targets. The agent crawls their changelogs, brand mentions, and technical stack updates. Output is a 10-page market intelligence PDF."
  },
  {
    id: "swarm-sales",
    name: "Swarm Corporate Growth Team (Autonomous Sales)",
    description: "An elite multi-agent sales intelligence team. Coordinates Lead Infiltrators, Outreach Strategists, and Closing Architects to handle enterprise-grade sales pipelines autonomously via CrewAI.",
    price: 1999,
    category: "AI Agents",
    image: "/images/products/swarm-sales.png",
    inStock: true,
    rating: 5.0,
    features: ['Lead Scoring Engine', 'Multi-Agent Coordination', 'CRM Integration Ready', 'Automated Outreach Workflows', 'Full Source Code Included'],
    specs: { API: 'OpenAI / Claude', Framework: 'CrewAI', Format: 'Python', License: 'Master Resell Rights', Support: 'Priority Support', Components: '3+ Agents' },
    downloadUrl: "/downloads/swarm-sales.zip",
    installGuide: "### Growth Protocol\n1. **Environment**: `python -m venv venv` and activate.\n2. **Install**: `pip install 'crewai[tools]'`.\n3. **Auth**: Add `ANTHROPIC_API_KEY` to `.env`.\n4. **Run**: `python main.py`.\n\n### Workflow\nFeed client pain points into the hive-mind. The 'Sales Manager' scout identifies leads, the 'Architect' designs the pitch, and the 'Writer' generates a professional PDF proposal."
  },
  {
    id: "swarm-finance",
    name: "Swarm Finance Infiltrator (xAI Oracle)",
    description: "A high-speed financial market oracle powered by xAI Grok and Agno. Synthesizes real-time stock, crypto, and market telemetry data into actionable trading intelligence reports.",
    price: 2499,
    category: "AI Agents",
    image: "/images/products/swarm-finance.png",
    inStock: true,
    rating: 5.0,
    features: ["xAI Grok Intelligence", "Real-time Market Telemetry", "Technical Analysis Engine", "Market Sentiment Scraping", "Streamlit Financial Dashboard"],
    specs: { API: 'xAI / OpenAI / YFinance', Framework: 'Agno', Format: 'Python / Streamlit', Support: 'Priority Support', License: 'Resell Rights' },
    downloadUrl: "/downloads/swarm-finance.zip",
    installGuide: "### Technical Oracle Setup\n1. **Install**: `pip install yfinance agno streamlit pandas`.\n2. **Uplink**: Add `XAI_API_KEY` to your secrets.\n3. **Launch**: `streamlit run finance_oracle.py`.\n\n### Data Flow\nEnter a ticker (AAPL, BTC). The 'Oracle Agent' pulls technical indicators (RSI, MACD), sentiment-scans social feeds, and returns a high-confidence Buy/Sell report."
  },
  {
    id: "swarm-cinema",
    name: "Swarm Cinema Infiltrator (AI Producer)",
    description: "A creative power-house for content creators and filmmakers. Coordinates between Narrative Architects and Mechanics Engineers to build complex worlds, scripts, and balanced production rulebooks autonomously.",
    price: 2999,
    category: "Entertainment AI",
    image: "/images/products/swarm-cinema.png",
    inStock: true,
    rating: 4.9,
    features: ["Narrative World Building", "Game Mechanics balancing", "Character Archetype design", "Rulebook Synthesis agent", "Unity/Unreal prompt generation"],
    specs: { API: 'OpenAI GPT-4', Framework: 'Agno', Target: 'Film & Game Devs', Format: 'Python', Support: 'Project Templates' },
    downloadUrl: "/downloads/swarm-cinema.zip",
    installGuide: "### Production Setup\n1. **Install**: `pip install agno openai pydantic`.\n2. **Launch**: `python creative_engine.py`.\n\n### Creative Workflow\nInput a concept (e.g. 'Neon Tokyo Noir'). The Narrative agent builds the lore, character arcs, and script beats. Mechanics agent generates balancing formulas for technical execution."
  },
  {
    id: "swarm-legal",
    name: "Swarm Legal Infiltrator (Contract Oracle)",
    description: "A multi-agent legal department that handles contract review, legal research, risk assessment, and compliance checks. It uses autonomous researcher and strategist agents to synthesize complex legal documents.",
    price: 2499,
    category: "AI Agents",
    image: "/images/products/swarm-legal.png",
    inStock: true,
    rating: 5.0,
    features: ["Contract Review Engine", "Legal Research Synthesis", "Risk Assessment Agent", "Specialize Legal Strategists", "Streamlit Command Center"],
    specs: { API: 'OpenAI / Anthropic', Framework: 'Phidata / Agno', Format: 'Python / Streamlit', License: 'Resell Rights', Support: 'Documentation Provided' },
    downloadUrl: "/downloads/swarm-legal.zip",
    installGuide: "### Deployment Guide\n1. **Install**: Python 3.10+.\n2. **Setup**: `pip install -r requirements.txt`.\n3. **Configure**: Add OpenAI API key to `.env`.\n4. **Launch**: `streamlit run app.py`.\n\n### Usage\nUpload any PDF contract. The 'Review Agent' scans for liabilities, and 'Risk Agent' generates a compliance scorecard with suggested clause changes."
  },
  {
    id: "sentinel-voyager",
    name: "Sentinel Global Voyager (Travel Planner)",
    description: "An autonomous travel planning system that creates personalized itineraries by researching destinations, flights, and hotels across the live web in real-time.",
    price: 1499,
    category: "AI Agents",
    image: "/images/products/sentinel-voyager.png",
    inStock: true,
    rating: 4.9,
    features: ["Autonomous Itinerary Generation", "Web-scale Destination Research", "Flight/Hotel Sourcing Intelligence", "Phidata Framework Powered", "Customizable Planner UI"],
    specs: { API: 'OpenAI, DuckDuckGo', Framework: 'Phidata', Format: 'Python / Streamlit', Support: 'Priority Email Support', Components: '3+ Agents' },
    downloadUrl: "/downloads/sentinel-voyager.zip",
    installGuide: "### Deployment\n1. **Prerequisites**: OpenAI API Key.\n2. **Setup**: `pip install -r requirements.txt`.\n3. **Run**: `python app.py`.\n\n### Workflow\nEnter location and budget. Voyager browses the live web for the best flight/hotel deals and compiles a full PDF itinerary."
  },
  {
    id: "swarm-voice",
    name: "Swarm Voice Orator (Narrative Synth)",
    description: "A voice-enabled AI agent that generates automated, narrated audio experiences for any text. Uses high-fidelity TTS and scriptwriting to deliver premium audio tours or narratives.",
    price: 1999,
    category: "Voice AI",
    image: "/images/products/swarm-voice.png",
    inStock: true,
    rating: 4.8,
    features: ["Location-aware Script Writing", "OpenAI TTS Voice Synthesis", "Interactive Map Markers Ready", "Bespoke Narrative Engine", "Ready for Mobile Deployment"],
    specs: { API: 'OpenAI GPT-4 & TTS', UI: 'Streamlit', Format: 'Python', Requirements: 'Python 3.10+', Logic: 'Narrative Synthesis' },
    downloadUrl: "/downloads/swarm-voice.zip",
    installGuide: "### Audio Protocol\n1. **Setup**: `pip install openai streamlit pydantic`.\n2. **Uplink**: Add `OPENAI_API_KEY` to secrets.\n3. **Launch**: `streamlit run oratory.py`.\n\n### Usage\nInput a subject. The AI drafts a script, synthesizes high-fidelity audio, and provides downloadable MP3 segments."
  },
  {
    id: "swarm-talent",
    name: "Swarm Talent Infiltrator (HR Oracle)",
    description: "An HR automation system that uses specialized agents to handle the hiring pipeline. Includes Job Spec automation and Resume screening intelligence.",
    price: 1799,
    category: "AI Agents",
    image: "/images/products/swarm-talent.png",
    inStock: true,
    rating: 4.7,
    features: ["Job Spec Automation Agent", "Candidate Screening Scorecard", "Automated Interview Scheduling", "Resume Selection Intelligence", "Team Orchestration Ready"],
    specs: { API: 'OpenAI, Phidata', Framework: 'Agno', Target: 'HR / Recruiters', Format: 'Python', Support: 'Lifetime Updates' },
    downloadUrl: "/downloads/swarm-talent.zip",
    installGuide: "### HR Deployment\n1. **Setup**: `pip install agno phi pypdf2`.\n2. **Uplink**: Add API keys to dashboard.\n3. **Run**: `python recruiter.py`.\n\n### Usage\nDrop resumes into the `/input` folder. Swarm ranks them by technical suitability and provides interview scripts for the top 5%."
  },
  {
    id: "swarm-property",
    name: "Swarm Property Infiltrator (Market Oracle)",
    description: "An autonomous property market analyzer that researches real estate listings and neighborhood metrics. Provides comprehensive investment advice by comparing live data against historical trends.",
    price: 1999,
    category: "AI Agents",
    image: "/images/products/swarm-property.png",
    inStock: true,
    rating: 4.9,
    features: ["Neighborhood Data Scraping", "Investment ROI Calculator", "Property Value Predictor", "Market Trend Analysis", "Automated Listing Research"],
    specs: { API: 'OpenAI, Zillow API Ready', Framework: 'Phidata', Format: 'Python / Streamlit', Support: 'Lifetime Access', Components: 'Real Estate Oracle' },
    downloadUrl: "/downloads/swarm-property.zip",
    installGuide: "### Property Protocol\n1. **Setup**: `pip install phidata streamlit googlemaps`.\n2. **Run**: `streamlit run real-estate.py`.\n\n### Usage\nEnter a target area. The Oracle pulls active listings and calculates real ROI based on local tax data and price history."
  },
  {
    id: "swarm-capital",
    name: "Swarm Capital Oracle (VC Due Diligence)",
    description: "The ultimate tool for VCs. Automatically researches startups, analyzes pitch decks using Vision AI, and provides objective due diligence reports in minutes.",
    price: 3499,
    category: "Finance & Investment",
    image: "/images/products/swarm-capital.png",
    inStock: true,
    rating: 5.0,
    features: ["Pitch Deck Vision Analysis", "Company Valuation Modeling", "Founder Background Check", "Competitive Landscape Scan", "Automated Due Diligence Docs"],
    specs: { API: 'Gemini Vision / OpenAI', Framework: 'Agno', Format: 'Python / Streamlit', License: 'Agency Whitelabel', Support: '1-on-1 Setup' },
    downloadUrl: "/downloads/swarm-capital.zip",
    installGuide: "### VC Protocol\n1. **Setup**: `pip install google-generativeai streamlit`.\n2. **Uplink**: Gemini 1.5 Pro API Key required.\n3. **Run**: `streamlit run investor.py`.\n\n### Usage\nUpload a PDF pitch deck. Swarm Vision scans slides, verifies LinkedIn profiles, and outputs a 10-page IC Memo."
  },
  {
    id: "sentinel-seo",
    name: "Sentinel SEO Infiltrator (Organic Hive)",
    description: "A multi-agent SEO agency that performs deep technical audits and keyword research. Coordinates between Crawler and Strategist agents to scale organic traffic.",
    price: 1599,
    category: "Marketing AI",
    image: "/images/products/sentinel-seo.png",
    inStock: true,
    rating: 4.8,
    features: ["Technical Crawler Agent", "Keyword Research strategist", "Content Optimization engine", "Backlink Analysis tools", "Growth Roadmap generation"],
    specs: { API: 'Anthropic / OpenAI / SerpApi', Framework: 'CrewAI / Phidata', Format: 'Python', Target: 'Digital Marketers', Support: 'Community Discord' },
    downloadUrl: "/downloads/sentinel-seo.zip",
    installGuide: "### SEO Protocol\n1. **Setup**: `pip install beautifulsoup4 serpapi crewai`.\n2. **Uplink**: Add SerpApi key to config.\n3. **Run**: `python audit.py`.\n\n### Usage\nInput a URL. Sentinel crawls the architecture, finds H1 gaps, and identifies 'Blue Ocean' keywords for immediate ranking."
  },
  {
    id: "1000-web-apps",
    name: "1000 Manually Tested Web Applications",
    description: "A comprehensive collection of 1000 manually tested web applications, including 20 free premium bonuses. Clean code, verified for functionality.",
    price: 200,
    category: "Web Development",
    image: "/images/products/1000-web-apps.png",
    inStock: true,
    rating: 4.8,
    features: ['1000+ Tested Applications', '20 Premium Bonuses', 'Clean Codebase', 'Instant Download'],
    specs: { Size: '1.2 GB', Format: 'PDF / Source Code', License: 'Personal & Commercial Use' },
    downloadUrl: "/downloads/1000-web-apps.pdf",
    installGuide: "### Installation\n1. Download and extract the archive.\n2. Reference the PDF index to find a project.\n3. Open in VS Code and follow local readme."
  },
  {
    id: "ultimate-web-dev-bundle",
    name: "Ultimate Web Development Bundle",
    description: "The ultimate toolkit for modern web developers. Premium templates, high-performance scripts, and essential UI kits curated for speed.",
    price: 300,
    category: "Bundles",
    image: "/images/products/ultimate-web-dev-bundle.png",
    inStock: true,
    rating: 4.9,
    features: ['Premium Templates', 'UI Kits', 'Scripts & Plugins', 'Developer Tools'],
    specs: { Format: 'ZIP / PDF', License: 'Royalty Free', Support: 'Email' },
    downloadUrl: "/downloads/ultimate-web-dev-bundle.pdf",
    installGuide: "### Setup\n1. Extract. 2. Browse components. 3. Copy-paste into your Next.js/React project."
  },
  {
    id: "ultimate-mega-bundle",
    name: "Ultimate Mega Bundle (Design & Code)",
    description: "A massive collection of digital assets, creative content, and high-performance code snippets.",
    price: 400,
    category: "Bundles",
    image: "/images/products/ultimate-mega-bundle.png",
    inStock: true,
    rating: 5.0,
    features: ['Huge Asset Library', 'High-Res Graphics', 'Ready-to-use Code'],
    specs: { Download: 'Instant', 'File Types': 'PSD, AI, HTML', 'Total Files': '5000+' },
    downloadUrl: "/downloads/ultimate-mega-bundle.pdf",
    installGuide: "### Access\n1. Download the PDF. 2. Use the private Mega.nz link inside to access the repository."
  },
  {
    id: "agency-seo-framework",
    name: "Scale-SEO Framework (Monthly Managed)",
    description: "A complete 4-step SEO framework designed for Indian e-commerce. Includes technical audit, keyword infiltration, and high-authority backlink building. We don't just 'do SEO' — we dominate search results.",
    price: 4999,
    category: "Agency Services",
    image: "/images/products/agency-seo.png",
    inStock: true,
    rating: 5.0,
    features: ['Technical Audit Protocol', 'Zero-Volume Keyword Strategy', 'High-DR Link Building', 'Monthly PDF Intel Report', 'Dedicated Account Oracle'],
    specs: { Type: 'Managed Service', Duration: 'Monthly', Targets: 'Search Dominance', Support: '24/7 Comms', Pricing: 'Starting From ₹4,999' },
    downloadUrl: "service_contract.pdf",
    installGuide: "### Strategic Onboarding\n1. **Uplink**: Book your strategy call after checkout.\n2. **Audit**: Our agents perform a technical sweep of your URL.\n3. **Deploy**: Content and links are deployed across our network."
  },
  {
    id: "agency-ppc-lab",
    name: "Elite-PPC Performance Lab (Ad Spend Management)",
    description: "High-velocity Meta and Google Ads management. We focus on ROAS (Return on Ad Spend) above all else. Optimized for scaling Indian brands from 10 to 1000 orders/day.",
    price: 2999,
    category: "Agency Services",
    image: "/images/products/agency-ppc.png",
    inStock: true,
    rating: 5.0,
    features: ['Real-time ROAS Tracking', 'A/B Creative Synthesis', 'Audience Infiltration', 'Competitor Ad Scraping', 'Weekly Performance Sync'],
    specs: { Platform: 'Meta / Google / LinkedIn', Target: 'Direct Response', Budget: 'Min. ₹2L/mo Managed', Support: 'Priority Support', License: 'Managed' },
    downloadUrl: "service_contract.pdf",
    installGuide: "### Performance Initiation\n1. **Protocol**: Shared access to your Ad Manager.\n2. **Creative**: We design the high-impact visual protocols.\n3. **Launch**: Scaling begins within 72 hours."
  }
];
