import { Product } from "./types";

export const products: Product[] = [
  {
    id: "notion-crm-protocol",
    name: "The Ultimate Freelancer CRM",
    description: "Your complete freelance operating system. This production-ready Notion template automates client invoicing, tracks every project milestone, and centralizes all client communication in one ruthlessly efficient dashboard. Includes 15 pre-built database views, automated status updates, and a revenue tracking system — ready to use in under 2 minutes.",
    price: 1499,
    originalPrice: 3899,
    category: "Notion Systems",
    image: "https://images.unsplash.com/photo-1618477388954-7852f32655ec?auto=format&fit=crop&q=80&w=800",
    inStock: true,
    rating: 5.0,
    features: ['1-Click Duplicate', 'Automated Invoicing', 'Client Portals', 'Task Prioritization Matrix', 'Revenue Dashboard'],
    specs: { Platform: 'Notion', Level: 'Beginner', Setup: '2 Mins', License: 'Personal', Support: 'Email' },
    downloadUrl: "/downloads/notion-crm-protocol.html",
    installGuide: "### Step 1 — Log In to Notion\nGo to notion.so and log in (or create a free account).\n\n### Step 2 — Open Your Delivery Page\nClick the download button to access your personalized delivery page with your private Notion template link.\n\n### Step 3 — Duplicate the Template\nClick the access link, then hit **Duplicate** (top-right corner of Notion) to copy the entire CRM into your workspace.\n\n### Step 4 — Configure Your Hub\nOpen the **⚙️ Settings** page inside your new CRM. Set your hourly rate, currency, and add your first client.\n\n### Step 5 — Start Tracking\nAdd your first project in the Projects board. The revenue dashboard auto-calculates based on your entries.\n\n📧 **Support**: support@digitalswarm.in | Subject: [NOTION CRM]",
    merchantId: "SYSTEM",
    isVerified: true
  },
  {
    id: "ai-social-automation",
    name: "AI Social Poster Blueprint",
    description: "A plug-and-play Make.com automation blueprint that monitors your RSS/content feeds, uses GPT-4 to generate platform-optimized captions with viral hooks, and auto-posts to X (Twitter) and LinkedIn on your schedule. Ships with 3 pre-built scenario templates — connect your accounts in under 10 minutes and never manually post again.",
    price: 1999,
    originalPrice: 4999,
    category: "No-Code Automations",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=800",
    inStock: true,
    rating: 4.9,
    features: ['Make.com Blueprint (.json)', 'GPT-4 Caption Engine', 'Auto-posts to X & LinkedIn', 'RSS Feed Watcher', 'Content Calendar Integration'],
    specs: { Platform: 'Make.com', API: 'OpenAI GPT-4', Output: 'X & LinkedIn', License: 'Business', Support: 'Email' },
    downloadUrl: "/downloads/ai-social-protocol.html",
    installGuide: "### Fulfillment (matches /downloads/ai-social-protocol.html)\n1. Open **`/downloads/ai-social-protocol.html`** after purchase — it is the canonical walkthrough.\n2. Build the Make.com scenario there (accounts, OpenAI key, RSS/social modules). Treat any blueprint import as **your** graph — Digital Swarm does not ship a hidden proprietary `.zip`.\n3. Add **`/downloads/swarm-paid-prompt-core.md`** if you want extra caption / campaign prompts beyond the page.\n\n📧 **Support**: support@digitalswarm.in | Subject: [SOCIAL BLUEPRINT]",
    merchantId: "SYSTEM",
    isVerified: true
  },
  {
    id: "cyberpunk-ui-kit",
    name: "Cyberpunk UI Kit Pro",
    description: "100+ production-ready, brutalist cyberpunk Figma components including buttons, cards, navigation bars, data dashboards, modals, and input fields — all with auto-layout, global color variables, and responsive constraints. Design stunning futuristic interfaces in minutes, not weeks. Commercial license included.",
    price: 2499,
    originalPrice: 5999,
    category: "Design Assets",
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800",
    inStock: true,
    rating: 5.0,
    features: ['100+ Figma Components', 'Global Color Variables', 'Auto-Layout & Constraints', 'Dark Mode Optimized', 'Commercial License'],
    specs: { Format: '.fig', Software: 'Figma (Free+)', Typography: 'Google Fonts', License: 'Commercial', Support: 'Lifetime' },
    downloadUrl: "/downloads/cyberpunk-ui-protocol.html",
    installGuide: "### Step 1 — Access Your Delivery Page\nClick download to open your delivery page and download the .fig file.\n\n### Step 2 — Import Into Figma\nOpen Figma, drag the .fig file onto the canvas or go to **File → Import**. The full component library loads instantly.\n\n### Step 3 — Install Required Fonts\nInstall from Google Fonts (free): **Outfit**, **Space Grotesk**, and **JetBrains Mono**.\n\n### Step 4 — Use Components\nOpen the **Assets panel** (Shift+I) in your project and search for any component. Drag onto canvas.\n\n### Step 5 — Customize Colors\nOpen **Edit → Edit Variables** to remap the entire color system to your brand in one click.\n\n📧 **Support**: support@digitalswarm.in | Subject: [CYBERPUNK UI KIT]",
    merchantId: "SYSTEM",
    isVerified: true
  },
  {
    id: "ai-executive-playbook",
    name: "The AI Executive Playbook",
    description: "A 50-page tactical PDF with 150+ battle-tested prompts for replacing entire business functions with AI. Covers lead generation, content marketing, competitive research, cold outreach, and executive decision-making — structured as 10 executable frameworks you implement immediately. Used by founders and CMOs across 30+ countries.",
    price: 999,
    originalPrice: 2499,
    category: "Playbooks",
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80&w=800",
    inStock: true,
    rating: 4.8,
    features: ['50-Page PDF Manifesto', '150+ Battle-Tested Prompts', '10 Executable Frameworks', 'Cold Outreach Templates', 'Competitive Research System'],
    specs: { Format: 'PDF', Length: '50 Pages', Tools: 'ChatGPT-4 / Claude', License: 'Personal', Support: 'Email' },
    downloadUrl: "/downloads/ai-executive-playbook.html",
    installGuide: "### Fulfillment (matches /downloads/ai-executive-playbook.html)\n1. After checkout, open your **delivery page** (`/downloads/ai-executive-playbook.html`) — it lists the real download buttons.\n2. Use **`/downloads/swarm-paid-prompt-core.md`** → **Section 14 — Executive & leadership** for board cadence, memos, and stakeholder narratives.\n3. Pair with **`saas-launch-checklist.txt`** and **`saas-tech-stack-audit.txt`** from `/downloads/` when you are sequencing launches.\n4. Run prompts in **ChatGPT / Claude** with your actual metrics and decisions — there is no separate encrypted PDF.\n\n📧 **Support**: support@digitalswarm.in | Subject: [EXECUTIVE PLAYBOOK]",
    merchantId: "SYSTEM",
    isVerified: true
  },
  {
    id: "ai-for-lawyers",
    name: "Elite Legal Protocol",
    description: "A comprehensive AI framework for law firms and solo practitioners. Includes 80+ legal-specific prompts for contract review, case research, client intake automation, and document drafting — pre-configured for ChatGPT-4 and Claude. Ships with Make.com workflow templates for client onboarding automation and a compliance checklist system.",
    price: 6999,
    originalPrice: 28999,
    category: "Legal",
    image: "/images/products/swarm-legal.png",
    inStock: true,
    rating: 5.0,
    features: ['80+ Legal AI Prompts', 'Contract Review System', 'Client Onboarding Automation', 'Case Research Framework', 'Make.com Workflow Templates'],
    specs: { Industry: 'Legal', Version: '2.4.0', Deploy: 'ChatGPT / Claude / Make.com', License: 'Enterprise', Support: 'Priority Email' },
    downloadUrl: "/downloads/swarm-legal-optimized.html",
    installGuide: "### Fulfillment (matches /downloads/swarm-legal-optimized.html)\n1. After checkout, open **`/downloads/swarm-legal-optimized.html`** — follow that page (it matches what customers see post-purchase).\n2. Download **`/downloads/swarm-paid-prompt-core.md`** → **Section 2 — Legal workflows** for clause passes, intake summaries, and memo outlines.\n3. Optionally pull **`saas-tech-stack-audit.txt`**, **`saas-launch-checklist.txt`**, **`design-system-tokens.css`** from `/downloads/` for ops hygiene.\n4. **Draft only** — have licensed counsel review anything client-facing.\n\n📧 **Priority Support**: support@digitalswarm.in | Subject: [LEGAL PROTOCOL]",
    merchantId: "SYSTEM",
    isVerified: true
  },
  {
    id: "ai-for-real-estate",
    name: "Elite Real Estate Protocol",
    description: "An end-to-end AI system for real estate agents and brokers. Contains 70+ prompts for lead qualification scripts, property listing copy, comparative market analysis, and buyer/seller objection handling. Includes a Make.com blueprint for automated lead pre-qualification and a Notion CRM template pre-configured for real estate pipelines.",
    price: 6999,
    originalPrice: 28999,
    category: "Real Estate",
    image: "/images/products/swarm-property.png",
    inStock: true,
    rating: 4.9,
    features: ['70+ Real Estate Prompts', 'Lead Pre-qualification Script', 'CMA Generation Framework', 'Listing Copy Generator', 'Automated Follow-up Blueprint'],
    specs: { Industry: 'Real Estate', Version: '2.4.0', Deploy: 'ChatGPT / Claude / Make.com', License: 'Enterprise', Support: 'Priority Email' },
    downloadUrl: "/downloads/swarm-property-optimized.html",
    installGuide: "### Fulfillment (matches /downloads/swarm-property-optimized.html)\n1. Open **`/downloads/swarm-property-optimized.html`** after checkout — that page is the source of truth.\n2. Use **`/downloads/swarm-paid-prompt-core.md`** → **Section 3 — Real estate** for listings, CMA narratives, and objection scripts.\n3. Add the bundled `/downloads/` text + CSS assets linked on the delivery page when you want checklists and token scaffolding.\n4. Wire **Make.com** yourself if you automate follow-ups — no hidden blueprint archive is bundled.\n\n📧 **Priority Support**: support@digitalswarm.in | Subject: [REAL ESTATE PROTOCOL]",
    merchantId: "SYSTEM",
    isVerified: true
  },
  {
    id: "ai-for-finance",
    name: "Elite Finance Protocol",
    description: "A professional AI toolkit for financial analysts, advisors, and fintech operators. Contains 90+ prompts for portfolio analysis, market research synthesis, risk assessment narratives, and financial report generation. Includes spreadsheet automation templates and a Python-ready data analysis framework for quantitative workflows.",
    price: 6999,
    originalPrice: 28999,
    category: "Finance",
    image: "/images/products/swarm-finance.png",
    inStock: true,
    rating: 5.0,
    features: ['90+ Finance AI Prompts', 'Risk Assessment Framework', 'Portfolio Analysis System', 'Report Generation Templates', 'Python Data Analysis Kit'],
    specs: { Industry: 'Finance', Version: '2.4.0', Deploy: 'ChatGPT / Claude / Python', License: 'Enterprise', Support: 'Priority Email' },
    downloadUrl: "/downloads/swarm-capital-optimized.html",
    installGuide: "### Fulfillment (matches /downloads/swarm-capital-optimized.html)\n1. Open **`/downloads/swarm-capital-optimized.html`** after checkout.\n2. Use **`/downloads/swarm-paid-prompt-core.md`** → **Section 4 — Finance & capital** for research snapshots, risk narratives, and board skeletons.\n3. Paste **your** data into ChatGPT / Claude — no bundled Python repo ships with this SKU.\n4. Optional scripts or sheets are **yours to build** on top of the prompt outputs.\n\n📧 **Priority Support**: support@digitalswarm.in | Subject: [FINANCE PROTOCOL]",
    merchantId: "SYSTEM",
    isVerified: true
  },
  {
    id: "ai-for-healthcare",
    name: "Elite Healthcare Protocol",
    description: "A HIPAA-conscious AI framework for healthcare providers and medical practices. Contains 75+ prompts for clinical documentation drafting, patient communication templates, diagnostic research summarisation, and workflow optimization. Includes appointment scheduling automation blueprints and a patient FAQ generation system.",
    price: 6999,
    originalPrice: 28999,
    category: "Healthcare",
    image: "https://images.unsplash.com/photo-1576091160550-217359f4ecf8?auto=format&fit=crop&q=80&w=800",
    inStock: true,
    rating: 5.0,
    features: ['75+ Healthcare AI Prompts', 'Clinical Documentation Drafts', 'Patient Communication Templates', 'Scheduling Automation Blueprint', 'HIPAA Usage Guidance'],
    specs: { Industry: 'Healthcare', Version: '2.4.0', Deploy: 'ChatGPT / Claude (HIPAA Mode)', License: 'Enterprise', Support: 'Priority Email' },
    downloadUrl: "/downloads/swarm-voice.html",
    installGuide: "### Fulfillment (matches /downloads/swarm-voice.html)\n1. Open **`/downloads/swarm-voice.html`** after checkout.\n2. Use **`/downloads/swarm-paid-prompt-core.md`** → **Section 5 — Healthcare documentation** for SOAP drafts, patient comms, and AI-usage checklist prompts.\n3. Read the **clinical notice** on the delivery page — outputs require licensed practitioner review.\n4. Scheduling automation is **Bring Your Own** Make.com/Zapier if you want it.\n\n📧 **Priority Support**: support@digitalswarm.in | Subject: [HEALTHCARE PROTOCOL]",
    merchantId: "SYSTEM",
    isVerified: true
  },
  {
    id: "ai-for-marketing",
    name: "Elite Digital Marketing Protocol",
    description: "A full-stack AI marketing system for agencies, growth teams, and solo marketers. Contains 95+ prompts for SEO content strategy, paid ad copy, email sequences, social media calendars, and conversion rate optimization. Includes a 90-day content calendar template, Google Ads prompt stack, and a competitor analysis framework that runs in 15 minutes.",
    price: 6999,
    originalPrice: 28999,
    category: "Digital Marketing",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800",
    inStock: true,
    rating: 4.9,
    features: ['95+ Marketing AI Prompts', '90-Day Content Calendar', 'Google Ads Copy System', 'Email Sequence Generator', 'Competitor Analysis Framework'],
    specs: { Industry: 'Digital Marketing', Version: '2.4.0', Deploy: 'ChatGPT / Claude / Make.com', License: 'Enterprise', Support: 'Priority Email' },
    downloadUrl: "/downloads/sentinel-seo-optimized.html",
    installGuide: "### Fulfillment (matches /downloads/sentinel-seo-optimized.html)\n1. Open **`/downloads/sentinel-seo-optimized.html`** after checkout — that page lists the real assets.\n2. Use **`/downloads/swarm-paid-prompt-core.md`** → **Section 6 — Marketing & SEO** for calendars, ad angles, and competitor snapshots.\n3. Spreadsheets and ad platforms are **yours** — there is no hidden xlsx/zip of fake folders.\n\n📧 **Priority Support**: support@digitalswarm.in | Subject: [MARKETING PROTOCOL]",
    merchantId: "SYSTEM",
    isVerified: true
  },
  {
    id: "ai-for-copywriting",
    name: "Elite Copywriting Protocol",
    description: "A conversion-focused AI writing system for marketers, founders, and professional copywriters. Contains 85+ prompts for sales pages, cold email sequences, VSL scripts, LinkedIn posts, and product descriptions — structured around AIDA, PAS, and StoryBrand frameworks. Includes a brand voice calibration system and A/B testing prompt generator.",
    price: 6999,
    originalPrice: 28999,
    category: "Copywriting",
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&q=80&w=800",
    inStock: true,
    rating: 5.0,
    features: ['85+ Copywriting Prompts', 'Sales Page Generator', 'Cold Email Sequences', 'VSL Script Framework', 'Brand Voice Calibration System'],
    specs: { Industry: 'Copywriting', Version: '2.4.0', Deploy: 'ChatGPT / Claude', License: 'Enterprise', Support: 'Priority Email' },
    downloadUrl: "/downloads/swarm-content-architect.html",
    installGuide: "### Fulfillment (matches /downloads/swarm-content-architect.html)\n1. Open **`/downloads/swarm-content-architect.html`** after checkout.\n2. Use **`/downloads/swarm-paid-prompt-core.md`** → **Section 7 — Copywriting & conversion** for voice, long-form, and CTA passes.\n3. No bundled “sales-page-framework” folder — everything ships as Markdown + the delivery HTML links.\n\n📧 **Priority Support**: support@digitalswarm.in | Subject: [COPYWRITING PROTOCOL]",
    merchantId: "SYSTEM",
    isVerified: true
  },
  {
    id: "ai-for-saas",
    name: "Elite SaaS Protocol",
    description: "A data-driven AI system for SaaS founders, product managers, and customer success teams. Contains 80+ prompts for churn prevention conversations, onboarding email sequences, feature announcement copy, NPS response handling, and user interview synthesis. Includes a predictive churn scoring framework and a user feedback analysis pipeline.",
    price: 6999,
    originalPrice: 28999,
    category: "SaaS",
    image: "https://images.unsplash.com/photo-1551288049-bbbda5366991?auto=format&fit=crop&q=80&w=800",
    inStock: true,
    rating: 5.0,
    features: ['80+ SaaS-Specific Prompts', 'Churn Prevention Playbook', 'Onboarding Email Sequences', 'User Interview Synthesis', 'NPS Response Framework'],
    specs: { Industry: 'SaaS', Version: '2.4.0', Deploy: 'ChatGPT / Claude / Make.com', License: 'Enterprise', Support: 'Priority Email' },
    downloadUrl: "/downloads/swarm-uiux-auditor.html",
    installGuide: "### Fulfillment (matches /downloads/swarm-uiux-auditor.html)\n1. Open **`/downloads/swarm-uiux-auditor.html`** after checkout.\n2. Use **`/downloads/swarm-paid-prompt-core.md`** → **Section 8 — SaaS & product** for churn narratives, onboarding comms, and research synthesis.\n3. Add **`saas-launch-checklist.txt`** / **`saas-tech-stack-audit.txt`** from `/downloads/` when the delivery page links them.\n\n📧 **Priority Support**: support@digitalswarm.in | Subject: [SAAS PROTOCOL]",
    merchantId: "SYSTEM",
    isVerified: true
  },
  {
    id: "ai-for-ecommerce",
    name: "Elite E-commerce Protocol",
    description: "A revenue-maximizing AI system for e-commerce brands on Shopify, WooCommerce, or any platform. Contains 85+ prompts for product description generation, abandoned cart email sequences, Facebook/Instagram ad copy, influencer outreach templates, and seasonal campaign planning. Includes a dynamic pricing analysis framework and a customer persona builder.",
    price: 6999,
    originalPrice: 28999,
    category: "E-commerce",
    image: "https://images.unsplash.com/photo-1557821552-17105176677c?auto=format&fit=crop&q=80&w=800",
    inStock: true,
    rating: 5.0,
    features: ['85+ E-commerce Prompts', 'Product Description Generator', 'Abandoned Cart Email System', 'Social Ad Copy Stack', 'Customer Persona Builder'],
    specs: { Industry: 'E-commerce', Version: '2.4.0', Deploy: 'ChatGPT / Claude / Make.com', License: 'Enterprise', Support: 'Priority Email' },
    downloadUrl: "/downloads/ai-services-agency.html",
    installGuide: "### Fulfillment (matches /downloads/ai-services-agency.html)\n1. Open **`/downloads/ai-services-agency.html`** after checkout.\n2. Use **`/downloads/swarm-paid-prompt-core.md`** → **Section 9 — E-commerce & DTC** for PDP copy, lifecycle email angles, and promo planning.\n3. Cart automation is **Bring Your Own** Make.com/Klaviyo — no secret `email-flows/` zip ships with the purchase.\n\n📧 **Priority Support**: support@digitalswarm.in | Subject: [ECOMMERCE PROTOCOL]",
    merchantId: "SYSTEM",
    isVerified: true
  },
  {
    id: "sentinel-research-infiltrator",
    name: "Sentinel Research Infiltrator",
    description: "An autonomous AI research agent built for deep competitive intelligence and market mapping. Pre-built prompt chains and Make.com automation workflows aggregate data from 40+ public sources, synthesize competitor positioning, and generate structured intelligence reports — in a fraction of the time of manual research. Used by strategy consultants and growth teams globally.",
    price: 14999,
    originalPrice: 79999,
    category: "AI Agent",
    image: "/images/products/sentinel-research.png",
    inStock: true,
    rating: 5.0,
    features: ['Deep Competitive Analysis System', 'Market Mapping Prompts', 'Intelligence Report Generator', 'Make.com Surveillance Automation', 'Strategic Briefing Templates'],
    specs: { Agent: 'Sentinel', Class: 'Research', Deploy: 'ChatGPT / Claude / Make.com', License: 'Elite', Support: '24/7 Priority' },
    downloadUrl: "/downloads/sentinel-research-optimized.html",
    installGuide: "### Fulfillment (matches /downloads/sentinel-research-optimized.html)\n1. Open **`/downloads/sentinel-research-optimized.html`** after checkout.\n2. Use **`/downloads/swarm-paid-prompt-core.md`** → **Section 1 — Research & competitive intel** for scan plans, synthesis memos, and source hygiene.\n3. Make.com graphs are **yours to build** from the page guidance — Digital Swarm does not ship a hidden `sentinel-monitor.json` bundle.\n\n📧 **24/7 Support**: support@digitalswarm.in | Subject: [SENTINEL AGENT]",
    merchantId: "SYSTEM",
    isVerified: true
  },
  {
    id: "cinema-infiltrator",
    name: "Swarm Cinema Infiltrator",
    description: "A specialized AI agent for video creators, filmmakers, and content studios. Contains prompt chains for scriptwriting, shot list generation, visual style briefs, voice-over scripts, and video SEO. Includes Make.com blueprints for automating video distribution across YouTube, Instagram Reels, and TikTok simultaneously after a single upload.",
    price: 14999,
    originalPrice: 79999,
    category: "AI Agent",
    image: "/images/products/swarm-cinema.png",
    inStock: true,
    rating: 5.0,
    features: ['Script Generation System', 'Shot List AI Framework', 'Visual Style Brief Generator', 'Multi-Platform Distribution Automation', 'Video SEO Optimizer'],
    specs: { Agent: 'Swarm', Class: 'Cinema', Deploy: 'ChatGPT / Claude / Make.com', License: 'Elite', Support: '24/7 Priority' },
    downloadUrl: "/downloads/swarm-cinema.html",
    installGuide: "### Fulfillment (matches /downloads/swarm-cinema.html)\n1. Open **`/downloads/swarm-cinema.html`** after checkout.\n2. Use **`/downloads/swarm-paid-prompt-core.md`** → **Section 11 — Cinema & video** for scripts, shot plans, and packaging copy.\n3. Multi-platform posting is **your** Make.com graph if you want it — no proprietary distribution zip is included.\n\n📧 **24/7 Support**: support@digitalswarm.in | Subject: [CINEMA AGENT]",
    merchantId: "SYSTEM",
    isVerified: true
  },
  {
    id: "finance-infiltrator",
    name: "Swarm Finance Agent",
    description: "An autonomous AI agent engineered for financial analysts, CFOs, and investment firms. Delivers high-frequency market research, automated financial modelling prompt chains, risk-scenario generation, and regulatory compliance summaries. Includes a Python-compatible data pipeline and a board-level financial reporting framework.",
    price: 14999,
    originalPrice: 79999,
    category: "AI Agent",
    image: "/images/products/swarm-finance.png",
    inStock: true,
    rating: 5.0,
    features: ['Autonomous Market Research', 'Financial Modelling Prompts', 'Risk Scenario Generator', 'Regulatory Compliance Summaries', 'Board Report Automation'],
    specs: { Agent: 'Swarm', Class: 'Finance', Deploy: 'ChatGPT / Claude / Python', License: 'Elite', Support: '24/7 Priority' },
    downloadUrl: "/downloads/swarm-finance-optimized.html",
    installGuide: "### Fulfillment (matches /downloads/swarm-finance-optimized.html)\n1. Open **`/downloads/swarm-finance-optimized.html`** after checkout.\n2. Use **`/downloads/swarm-paid-prompt-core.md`** → **Section 4 — Finance & capital** (and **Section 1** when you need raw intel framing) for memos, scenarios, and board-ready skeletons.\n3. Paste **your** figures and sources — no bundled `python-pipeline/` archive ships with this SKU.\n\n📧 **24/7 Support**: support@digitalswarm.in | Subject: [FINANCE AGENT]",
    merchantId: "SYSTEM",
    isVerified: true
  },
  {
    id: "sales-infiltrator",
    name: "Swarm Sales Infiltrator",
    description: "An aggressive AI sales system for B2B founders, SDRs, and account executives. Contains 100+ prompts for cold email personalization at scale, LinkedIn outreach sequences, objection handling scripts, and proposal writing. Includes a Make.com blueprint that automates prospecting research and first-touch personalized outreach — saving 3+ hours per day.",
    price: 14999,
    originalPrice: 79999,
    category: "AI Agent",
    image: "/images/products/swarm-sales.png",
    inStock: true,
    rating: 5.0,
    features: ['100+ Sales AI Prompts', 'Cold Email Personalization Engine', 'LinkedIn Outreach Sequences', 'Objection Handling Scripts', 'Prospecting Automation Blueprint'],
    specs: { Agent: 'Swarm', Class: 'Sales', Deploy: 'ChatGPT / Claude / Make.com', License: 'Elite', Support: '24/7 Priority' },
    downloadUrl: "/downloads/swarm-sales-optimized.html",
    installGuide: "### Fulfillment (matches /downloads/swarm-sales-optimized.html)\n1. Open **`/downloads/swarm-sales-optimized.html`** after checkout.\n2. Use **`/downloads/swarm-paid-prompt-core.md`** → **Section 10 — Sales & outbound** for cold opens, sequences, and objection passes.\n3. Prospecting automation is **your** Make.com wiring — there is no hidden `swarm-prospector.json` drop.\n\n📧 **24/7 Support**: support@digitalswarm.in | Subject: [SALES AGENT]",
    merchantId: "SYSTEM",
    isVerified: true
  },
  {
    id: "ai-for-recruitment",
    name: "Elite Recruitment Protocol",
    description: "A comprehensive AI hiring system for HR managers, talent acquisition teams, and recruitment agencies. Contains 70+ prompts for job description writing, resume screening criteria, interview question generation, and candidate evaluation rubrics. Includes an automated sourcing workflow for LinkedIn and a structured interview-to-offer pipeline.",
    price: 6999,
    originalPrice: 28999,
    category: "Recruitment",
    image: "/images/products/swarm-talent.png",
    inStock: true,
    rating: 4.9,
    features: ['70+ Recruitment Prompts', 'JD Generator & Optimizer', 'Resume Screening Framework', '200+ Interview Question Bank', 'Automated Sourcing Blueprint'],
    specs: { Industry: 'Recruitment', Version: '2.4.0', Deploy: 'ChatGPT / Claude / Make.com', License: 'Enterprise', Support: 'Priority Email' },
    downloadUrl: "/downloads/swarm-talent-optimized.html",
    installGuide: "### Fulfillment (matches /downloads/swarm-talent-optimized.html)\n1. Open **`/downloads/swarm-talent-optimized.html`** after checkout.\n2. Use **`/downloads/swarm-paid-prompt-core.md`** → **Section 12 — Recruitment** for JDs, rubrics, and interview plans.\n3. ATS / LinkedIn automation is **Bring Your Own** if you want it.\n\n📧 **Priority Support**: support@digitalswarm.in | Subject: [RECRUITMENT PROTOCOL]",
    merchantId: "SYSTEM",
    isVerified: true
  },
  {
    id: "ai-for-home-services",
    name: "Elite Home Services Protocol",
    description: "A complete AI operations system for plumbing, HVAC, electrical, cleaning, and landscaping businesses. Contains 65+ prompts for automated quote generation, job scheduling communication, customer follow-up sequences, Google review request scripts, and seasonal promotion copy. Includes a dispatch optimization framework and customer portal setup guide.",
    price: 6999,
    originalPrice: 28999,
    category: "Home Services",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=800",
    inStock: true,
    rating: 5.0,
    features: ['65+ Home Services Prompts', 'Automated Quote Generator', '5-Star Review Request System', 'Dispatch Communication Templates', 'Seasonal Promotion Campaigns'],
    specs: { Industry: 'Home Services', Version: '2.4.0', Deploy: 'ChatGPT / Claude / Make.com', License: 'Enterprise', Support: 'Priority Email' },
    downloadUrl: "/downloads/sentinel-voyager.html",
    installGuide: "### Fulfillment (matches /downloads/sentinel-voyager.html)\n1. Open **`/downloads/sentinel-voyager.html`** after checkout.\n2. Use **`/downloads/swarm-paid-prompt-core.md`** → **Section 13 — Home services trades** for quotes, dispatch comms, and review asks.\n3. CRM / SMS wiring is **yours** — fulfillment is Markdown + the delivery page, not a nested zip of fake folders.\n\n📧 **Priority Support**: support@digitalswarm.in | Subject: [HOME SERVICES PROTOCOL]",
    merchantId: "SYSTEM",
    isVerified: true
  },
  {
    id: "starter-kit",
    name: "Digital Swarm Starter Kit",
    description: "Licensed prompt + checklist bundle for solo builders: the Swarm paid prompt core (Markdown), stack audit, launch checklist, token CSS, and the compact prompt library — everything ships inside a verified ZIP so you can execute immediately in ChatGPT / Claude.",
    price: 1499,
    originalPrice: 4999,
    category: "Source Code",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=800",
    inStock: true,
    rating: 5.0,
    features: ['swarm-paid-prompt-core.md', 'Launch + stack audits', 'Design token CSS', 'Portable ZIP fulfillment'],
    specs: { Format: 'ZIP + Markdown', Models: 'ChatGPT / Claude', License: 'Single seat', Support: 'Email' },
    downloadUrl: "/downloads/starter-kit.zip",
    installGuide: "### Step 1 — Download the ZIP\nYour purchase delivers `starter-kit.zip` from `/downloads/starter-kit.zip` (also linked post-checkout). Unzip it — you will find `READ_ME_FIRST.txt`, `swarm-paid-prompt-core.md` (master prompts), `ai-prompt-library.txt`, `saas-launch-checklist.txt`, `saas-tech-stack-audit.txt`, and `design-system-tokens.css`.\n\n### Step 2 — Start in the Markdown core\nOpen `swarm-paid-prompt-core.md` and jump to the section that matches your roadmap (Executive, Marketing, SaaS, etc.). Copy prompts into ChatGPT or Claude with your real context.\n\n📧 **Support**: support@digitalswarm.in | Subject: [STARTER KIT]",
    merchantId: "SYSTEM",
    isVerified: true
  },
  {
    id: "nextjs-saas-kit",
    name: "Digital Swarm Professional Kit",
    description: "Everything in the Starter Kit plus a battle-tested React/Tailwind sample module (`cyberpunk-mini-ui-kit.tsx`) you can drop into your own codebase. Same honest scope: prompts, checklists, and UI scaffolding — not a leaked production monorepo.",
    price: 3999,
    originalPrice: 9999,
    category: "Source Code",
    image: "https://images.unsplash.com/photo-1542831371-29b0f74f9713?auto=format&fit=crop&q=80&w=800",
    inStock: true,
    rating: 5.0,
    features: ['Everything in Starter', 'cyberpunk-mini-ui-kit.tsx sample', 'Same prompt core', 'ZIP fulfillment'],
    specs: { Format: 'ZIP + Markdown + TSX sample', Models: 'ChatGPT / Claude', License: 'Single seat', Support: 'Email' },
    downloadUrl: "/downloads/pro-kit.zip",
    installGuide: "### Step 1 — Download the ZIP\n`pro-kit.zip` contains everything in the Starter Kit **plus** `cyberpunk-mini-ui-kit.tsx` (a compact React/Tailwind sample module you can adapt). Read `READ_ME_FIRST.txt` inside the archive for the manifest.\n\n### Step 2 — Wire prompts + UI sample\nUse `swarm-paid-prompt-core.md` for production-grade prompt chains, then reference `cyberpunk-mini-ui-kit.tsx` when you want UI scaffolding — it is a sample, not a full cloned production repo.\n\n📧 **Support**: support@digitalswarm.in | Subject: [PRO KIT]",
    merchantId: "SYSTEM",
    isVerified: true
  }
];
