-- ⚠️  This file is DEPRECATED.
-- The combined schema + seed is now in src/db/schema.sql
-- Run schema.sql in your Supabase SQL Editor instead.
--
-- That file handles:
--   - Table creation (with IF NOT EXISTS — safe to run on existing DBs)
--   - Missing column additions (ALTER TABLE ADD COLUMN IF NOT EXISTS)
--   - Row Level Security policies
--   - Auto updated_at triggers
--   - Full product catalog seed (with ON CONFLICT DO UPDATE — idempotent)
